#pragma once
#define MAX_MENUE_NUMBER 4	//ÉÅÉjÉÖÅ[ÇÃêîÅ@
#define START_MENUE_NUMBER 0
#define EXIT_MENUE_NUMBER 3
#define MANUAL_MENUE_NUMBER 1
#define KEYCON_MENUE_NUMBER 2
#define MOVE_MENUE_DIST 100
#define TITLEMEN_BASIC_PLACE_Y 300
#define TITLEMEN_BASIC_PLACE_X 220